Repository wecode-bootcamp-korea/26-2nd-Prep-frontend, pull requests merged in 2021-11, with the labels that each got.

#1 [26기 양성호] nav바 레이아웃 완료
  public/images/category.png
  public/images/feed.png
  public/images/login.png
  public/images/logo.png
  public/images/mypage.png
  public/images/sample.jpg
  public/images/돋보기.png
  public/index.html
  src/components/Nav/Nav.js
Labels: Status: 리뷰 요청

#5 [26기 장연정] 상세페이지 레이아웃 구현
  public/data/ProductData.json
  public/data/ReviewData.json
  public/data/StarRate.json
  public/data/data.json
  public/images/파란별들.png
  public/images/회색별들.png
  src/pages/DetailPage/Components/ProductHead.js
  src/pages/DetailPage/Components/Review.js
  src/pages/DetailPage/Components/ReviewInputBox.js
  src/pages/DetailPage/Components/StarRateInput.js
  src/pages/DetailPage/Components/StarRating.js
  src/pages/DetailPage/DetailPage.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#3 [26기 양성호] footer 레이아웃 완료
  public/images/playstore.png
  src/components/Footer/Footer.js
Labels: Status: 리뷰 요청

#4 [26기 박보라] Refactor : 리뷰 반영 및 Refactoring 완료
  .gitignore
  public/images/kakao_login.png
  public/images/readme.md
  src/Router.js
  src/pages/Login/Kakao.js
  src/pages/Login/Login.js
  src/pages/Login/OAuth.js
  yarn.lock
Labels: Status: Accepted

#6 [26기 장연정] Add: 상세페이지 추가 기능 구현 중
  src/index.js
  src/pages/DetailPage/Components/ProductHead.js
  src/pages/DetailPage/Components/Review.js
  src/pages/DetailPage/Components/ReviewInputBox.js
  src/pages/DetailPage/Components/StarRateInput.js
  src/pages/DetailPage/Components/StarRating.js
  src/pages/DetailPage/DetailPage.js
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#8 [26기 박보라] 리스트 페이지 기능 구현 완료
  public/images/check.png
  src/Router.js
  src/config.js
  src/pages/ListPage/ListHeader/ListMenu/CategoryMenu.js
  src/pages/ListPage/ListHeader/ListMenu/CategoryMenuData.js
  src/pages/ListPage/ListHeader/ListMenu/FilteringMenu.js
  src/pages/ListPage/ListHeader/ListMenu/FilteringMenuData.js
  src/pages/ListPage/ListHeader/components/FilterContent.js
  src/pages/ListPage/ListHeader/components/FilterMenuData.js
  src/pages/ListPage/ListHeader/components/FilterModal.js
  src/pages/ListPage/ListPage.js
  src/pages/ListPage/Products/Product.js
  yarn.lock
Labels: Status: 리뷰 요청
